export default [
  {
    file: "EICHBAUM  et al - Opportunities and challenges in NS and SS partnerships in Covid-19 - AoGH 2021.pdf",
    title: "",
    author: "Quentin Eichbaum",
    date: "",
    description: "",
  },
  {
    file: "EICHBAUM  et al - The Consortium of New Southern AFrican Medical Schools_ A new South-South-North network - Knowledge for a Sustainable World, Ch 10, SANORD 2015.pdf",
    title: "",
    author: "Quentin Eichbaum",
    date: "",
    description: "",
  },
  {
    file: "EICHBAUM  et al. - Challenges and Opportunities for New Medical Schools in Africa - Lancet 2014.pdf",
    title: "",
    author: "Quentin Eichbaum",
    date: "",
    description: "",
  },
  {
    file: "EICHBAUM - Acquired and Participatory Competencies in Health Professions Education- Definition and Assessment in Global Health - ACAD MED 2016.pdf",
    title: "",
    author: "Quentin Eichbaum",
    date: "",
    description: "",
  },
  {
    file: "EICHBAUM - The_Problem_With_Competencies_in_Global_Health Education - Acad Med April 2015.pdf",
    title: "",
    author: "Quentin Eichbaum",
    date: "",
    description: "",
  },
  {
    file: "Eichbaum et al -.pdf",
    title: "",
    author: "Quentin Eichbaum",
    date: "",
    description: "",
  },
  {
    file: "Eichbaum et al - Decolonizing Global Health Education- Rethinking Institutional Partnerships and Approaches - Academic Medicine 2021.pdf",
    title: "",
    author: "Quentin Eichbaum",
    date: "",
    description: "",
  },
  {
    file: "EICHBAUM et al - New Medical Schools in Africa- Challenges and Opportunities. 59 7 CONSAMS and Value of Working in Consortia - ANNALS OF GLOBAL HEALTH 2015.pdf",
    title: "",
    author: "Quentin Eichbaum",
    date: "",
    description: "",
  },
];
